### ISSUE TITLE
TypeError: atom.packages.activatePackage(...).then(...).fail is not a function

### ISSUE THREAD

**Issue by olmokramer** [abe33/atom-utils#2]
**Reproduction**

1. Build latest version of Atom
2. Install tree-view-breadcrumb: `apm install tree-view-breadcrumb`
3. Load Atom, error is logged in the terminal, but there's no error notification (`atom.notifications.addError`) in the top right corner of Atom's window.

**System details**

* Atom 1.2.0-dev-fdbe65b (built from source)
* Debian 9

**Stack trace**

```
TypeError: atom.packages.activatePackage(...).then(...).fail is not a function
  at /home/olmo/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/atom-utils.js:27:14
  at Array.forEach (native)
  at module.exports.requirePackages (/home/olmo/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/atom-utils.js:23:25)
  at module.exports.requirePackages (/home/olmo/.atom/packages/tree-view-breadcrumb/node_modules/atom-utils/lib/atom-utils.js:8:14)
  at Object.module.exports.activate (/home/olmo/.atom/packages/tree-view-breadcrumb/lib/tree-view-breadcrumb.coffee:34:5)
  at Package.module.exports.Package.activateNow (/usr/local/share/atom/resources/app.asar/src/package.js:246:19)
  at /usr/local/share/atom/resources/app.asar/src/package.js:226:32
  at Package.module.exports.Package.measure (/usr/local/share/atom/resources/app.asar/src/package.js:167:15)
  at /usr/local/share/atom/resources/app.asar/src/package.js:219:26
  at Package.module.exports.Package.activate (/usr/local/share/atom/resources/app.asar/src/package.js:215:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/share/atom/resources/app.asar/src/package-manager.js:484:21)
  at /usr/local/share/atom/resources/app.asar/src/package-manager.js:467:29
  at Config.module.exports.Config.transact (/usr/local/share/atom/resources/app.asar/src/config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/local/share/atom/resources/app.asar/src/package-manager.js:462:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/local/share/atom/resources/app.asar/src/package-manager.js:443:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/local/share/atom/resources/app.asar/src/atom.js:657:21)
  at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.keys.forEach.Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///usr/local/share/atom/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///usr/local/share/atom/resources/app.asar/static/index.js:35:9)
```

I think the error should be fixed if you use `Promise::catch` instead of `Promise::fail`

**Comment by abe33** [comment]
Hi @olmokramer, thank you for the report, I didn't noticed that activatePackage was finally using native Promise. I'll push patch soon.

**Comment by olmokramer** [comment]
Merci! :)
